### ISSUE TITLE
Ordered/Unordered lists not working

### ISSUE THREAD

**Issue by khursheedali38** [neutronX/django-markdownx#102]
Ordered list and Unordered lists are not working. I used almost all the markdown constructs to represent the list element, but markdown isn't identified to render in HTML.

I used  `+`, `-`, and `1.` for lists, none of them work.

Did anyone else face this issue?

**Comment by xenatisch** [comment]
The answer given to issue #97 applies to this, too. 

I will close this issue, but feel free to reopen it if you have any additional questions.
