### ISSUE TITLE
Image path inside an app

### ISSUE THREAD

**Issue by alaorneto** [neutronX/django-markdownx#104]
I'm following the tutorial to test markdownx, but I'm facing a problem.

My project is called "theproject", then I have my form inside an app, let's say "myapp".

I have set the following variables in my project's settings.py:

```
MEDIA_ROOT = BASE_DIR + '/media/'
# Markdownx configurations
MARKDOWNX_MEDIA_PATH = datetime.now().strftime('upload/%Y/%m/%d')
```

When I drag some jpeg to the editor, it gets upload to /theproject/media/upload/YYYY/MM/DD/.

But the GET request is being made to /myapp/upload/YYYY/MM/DD, so I get an 404 error and the image is not shown.

How can I solve this?

**Comment by xenatisch** [comment]
Apologies for the late response.

You solved it, or gave up, or still need help?

**Comment by alaorneto** [comment]
I gave up, actually.
