### ISSUE TITLE
Preview not working on outside admin (on frontend)

### ISSUE THREAD

**Issue by eriktelepovsky** [neutronX/django-markdownx#108]
Hi.

I have successfully configured markdown field and it works fine in the admin:

![image](https://user-images.githubusercontent.com/2685808/36620670-7a0355ae-18f4-11e8-972c-7a11aa851c80.png)

I also use it in my custom form on frontend, but unfortunately, the preview does not work. I can see the requests in the "Network" tab in the Google Chrome Developer Tools and I see the response is correctly returned:

![image](https://user-images.githubusercontent.com/2685808/36620693-9d87b2e0-18f4-11e8-89bd-d49e68454add.png)

I debugged **markdown.js** file at line 477:

```
xhr.success = function (response) {
    console.log('success');
    console.log(response);
    properties.preview.innerHTML = response;
    properties.editor = updateHeight(properties.editor);
    utils_1.triggerCustomEvent('markdownx.update', properties.parent, [response]);
};
```

and the result is, that "response" variable is always *null*:

![image](https://user-images.githubusercontent.com/2685808/36620769-ed94d696-18f4-11e8-9cda-02505faeace2.png)

Any idea what can cause the issue?

pip:

```
Django==2.0.2
django-markdownx==2.0.22
```

**Comment by xenatisch** [comment]
You debugged an intertwined, compiled JavaScript file. The `Request` class is fine -  I wrote it 2 or 3 years ago, and I have since used it in many, many projects. If there is a problem, it's not there; at least not in that method.

**Comment by eriktelepovsky** [comment]
Any idea where should I look elsewhere? The interesting fact is, the preview works in the Django admin but not on the frontend. But I can see the requests are being fired and the HTTP responses have correct content.

**Comment by xenatisch** [comment]
Well, the whole code would work if you delete the entire `settings.py` file, but that doesn't mean that it does what it is designed to do. So be very careful.

I cannot confirm anything - you have edited the wrong file. That file will be overwritten the moment someone recompiles the [TypeScript](https://github.com/neutronX/django-markdownx/tree/master/static-src/markdownx/js) file, which is the source code for the part of the API that is written in JavaScript .

That said, I am still unclear what your problem is. Give me a proper outline in the following order:
- What are you trying to do?
- What is the problem?
- What have you tried so far?
- Where have you received the instructions from?

**Comment by xenatisch** [comment]
Here is the [Request ](https://github.com/neutronX/django-markdownx/blob/master/static-src/markdownx/js/utils.ts#L167-L266) class, and here is [the part](https://github.com/neutronX/django-markdownx/blob/master/static-src/markdownx/js/utils.ts#L206-L214) you edited. It does nothing, until it is assigned to something.

What you need to do is to find out where the potential problem lies in [markdownx.ts](https://github.com/neutronX/django-markdownx/blob/master/static-src/markdownx/js/markdownx.ts) file.

**Comment by eriktelepovsky** [comment]
Yes, I understand it will be overwritten, I just wanted to point to the issue. I think it will be easier to demonstrate using screen recording. Please look into my video I just uploaded:

https://youtu.be/UEs6Hurr9BM

Btw. I haven't edited the part you pointed to, I edited the compiled output of this part:

https://github.com/neutronX/django-markdownx/blob/master/static-src/markdownx/js/markdownx.ts#L703

I can't figure out why the original code doesn't work by default in my project.

Thank you.

**Comment by xenatisch** [comment]
The question is, why is it working in one place, but not the other! 
Any terminal outputs?

**Comment by eriktelepovsky** [comment]
Nothing suspicious in output :/ My guess is a conflict with some other JavaScript library I use on the frontend. I'll investigate it.

**Comment by adi-** [comment]
Any updates?

**Comment by adi-** [comment]
No additional info... closing.
