### ISSUE TITLE
Django Admin - Inline Model

### ISSUE THREAD

**Issue by Erwol** [neutronX/django-markdownx#113]
Hello,

I've a django admin inline model which contains a MarkDownX field. Is there a way to display the markdown editor using this structure?

```
class ProjectDescriptionInline(CompactInline):
    model = ProjectDescription

@admin.register(Project)
class ProjectAdmin(admin.ModelAdmin):
    inlines = [
        ProjectDescriptionInline,
    ]
```

Thanks.

**Comment by adi-** [comment]
Yes, why not. Could you be more specific?

**Comment by adi-** [comment]
Is it still worrying you?

**Comment by Erwol** [comment]
Sorry for the extra - late answer. The issue was solved by a different person at the time. Thanks.

**Comment by dmwyatt** [comment]
@adi-  I think this should be re-opened.

This kind of works "out of the box".  You just add your inlines like you always would, and markdown previews work on the inlines...but only the initial "extra" inlines that are shown on initial page rendering.

If you add any more inlines by clicking the `+ Add another Model name here`, the new inlines do not show the markdown preview

**Comment by frandemona** [comment]
This worked for me! Thanks

> Theoretically (according to `MarkdownxModelAdmin` source code):
> 
> https://github.com/neutronX/django-markdownx/blob/8357e0a64e0548486ccab7f3039c3d30e7846d1f/markdownx/admin.py#L7-L16
> 
> It would be sufficient to do the following:
> 
> ```
> from markdownx.widgets import AdminMarkdownxWidget
> from markdownx.models import MarkdownxField
> 
> 
> class ProjectDescriptionInline(CompactInline):
>     model = ProjectDescription
>     formfield_overrides = {
>         MarkdownxField: {'widget': AdminMarkdownxWidget}
>     }
> ```
> 
> However, I cannot verify it because I am on Django-2.2 and Python-3.7.4 and I cannot use this plugin.
