### ISSUE TITLE
High time to move to GitLab

### ISSUE THREAD

**Issue by adi-** [neutronX/django-markdownx#119]

**Comment by e-ht** [comment]
You don't need GitLab any more than you need Github.  I would even go as far as saying you need Gitlab even less.  Don't make an emotional decision based on who just bought the VC funded thing you use and jump ship to another VC funded thing who's buyer hasn't been listed yet.

**Comment by adi-** [comment]
That has nothing to do with amotions but hard facts. I couldn’t agree more http://jacquesmattheij.com/what-is-wrong-with-microsoft-buying-github

**Comment by e-ht** [comment]
I'm just saying, maybe Microsoft or some other nefarious corp buys Gitlab or any other number of VC funded git hosts tomorrow, then where do you go?
