### ISSUE TITLE
Multiple editors with preview in one page

### ISSUE THREAD

**Issue by dhavalsavalia** [neutronX/django-markdownx#122]
I have followed http://neutronx.github.io/django-markdownx/js/docs/markdownx.html#MarkdownX docs but can't get it done properly.

![screen shot 2018-06-18 at 3 50 56 pm](https://user-images.githubusercontent.com/27001046/41530962-7c225130-730f-11e8-9dd0-b915f08c3bc2.png)

What is the correct way to setup two or more editors in the same page?

**Comment by dhavalsavalia** [comment]
@adi- Please suggest me. I have tried everything but can't get multiple editors on the same page.

**Comment by e-ht** [comment]
@dhavalsavalia have you run `collectstatic` on your project?

**Comment by dhavalsavalia** [comment]
Figured it out myself. Thank you so much!
