### ISSUE TITLE
Styling bar

### ISSUE THREAD

**Issue by jdhurwitz** [neutronX/django-markdownx#124]
Is there a configuration option to make a styling bar show up on a markdownx field, or does the end user just have to know how to use md in order to style? For example, as I'm typing now I can format using the bar above: 

<img width="718" alt="image" src="https://user-images.githubusercontent.com/9702107/43157580-4ccc70de-8f32-11e8-8f6d-2a04d39756f9.png">

**Comment by adi-** [comment]
No, there isn't. It was intentional.

**Comment by jdhurwitz** [comment]
sad
