### ISSUE TITLE
How to add rel="nofollow" attribute to all external links?

### ISSUE THREAD

**Issue by frkba** [neutronX/django-markdownx#125]
I'm looking for some way to add rel="nofollow" and target="_blank" attributes to all external links. Is there some way to do this? How to change the rendering of an element (for example I want to add some class or attribute to an element), whether it be ul, blockquote, table or any other HTML tag.

**Comment by adi-** [comment]
I guess you have two options:

* using Django/python handler (which seems to be better option)
* using Javascript handler

The first one could alter your code on the fly when python's Markdown is compiling the code. You could use and precompiler which alters your hyperlinks the way you want.

**Comment by adi-** [comment]
Please see https://neutronx.github.io/django-markdownx/customization.html#image-tags
