### ISSUE TITLE
Is that possible to show table from markdown 

### ISSUE THREAD

**Issue by rinkuameotech** [neutronX/django-markdownx#126]
I want to show the table from the table markdown text but I am unable to do  that it simply paste the same text in the markdown preview area
Is there anybody who can help me in this?

**Comment by rinkuameotech** [comment]
Thanks @adi-  It works for me also I want to ask for the design which we have to do in css right?

**Comment by rinkuameotech** [comment]
Thanks @adi-  thanks for your quick support it works for me

**Comment by adi-** [comment]
No probs.
