### ISSUE TITLE
Upload Image

### ISSUE THREAD

**Issue by jfajardo** [neutronX/django-markdownx#133]
I have this issue when upload a image
*Django 2.1
*django-markdownx==2.0.24

   ```
 file_size = getattr(upload, '_size')
AttributeError: 'InMemoryUploadedFile' object has no attribute '_size'
```

**Comment by jfajardo** [comment]
#129

**Comment by florimondmanca** [comment]
Also encountering this issue (django==2.1, django-markdownx==2.0.24, Python 3.7).
Is there a workaround? Simply don't use with Django 2.1 until the fix has been merged & released?
