### ISSUE TITLE
Image upload not working.

### ISSUE THREAD

**Issue by drivasperez** [neutronX/django-markdownx#138]
I haven't been able to get the drag-and-drop media upload function working. I'm very new to Django, so it might well be that I'm doing something really stupid, but I've spent several hours trying to work out what the issue might be, or find anyone in the usual places who has had the same issue, and haven't been able to.

My /media url is set up properly and works fine: if I put an `image.jpg` in my app's media folder and try to access it at `website.com/media/image.jpg`, it shows up in the browser. But after following the "Getting Started" section in the docs, and changing a `TextField` in my model into a `MarkdownxField`,  dragging an image onto the corresponding `MarkdownxFormField` doesn't do anything. Any text in the form field greys out, but no image is ever uploaded. 

Otherwise everything, works fine. Text is formatted according to the markdown in the field, and rendered appropriately next to it.

Is there an extra setup step I'm missing? Or is this a known issue with Django 2.1?

**Comment by JeroenvO** [comment]
Known issue: https://github.com/neutronX/django-markdownx/issues/133
The newest version directly from git works.

**Comment by adi-** [comment]
Yes, git already has fixed version. PyPi update is on the way...

**Comment by drivasperez** [comment]
Thanks a lot, and sorry for the issue duplication.

**Comment by adi-** [comment]
FYI: updated on PyPi
