### ISSUE TITLE
Upload image successfully, but preview failed

### ISSUE THREAD

**Issue by siqinghang** [neutronX/django-markdownx#139]
My configuration is as follows：
`MARKDOWNX_UPLOAD_URLS_PATH = '/markdownx/upload/'
MARKDOWNX_MEDIA_PATH = datetime.now().strftime('static/upload/%Y/%m/%d')`
![2018-10-21 14-46-53](https://user-images.githubusercontent.com/17929408/47264022-31819800-d540-11e8-8a96-7f6b27dadda8.png)
![2018-10-21 14-48-10](https://user-images.githubusercontent.com/17929408/47264028-5c6bec00-d540-11e8-9797-d4ec20e8b79a.png)

I need to add / to the left end of the automatically generated link in the preview to get the image.
How should I solve it?

**Comment by adi-** [comment]
I don't get your point. Could you be more specific?

**Comment by JeroenvO** [comment]
And what if you prepend an `/` to the `MARKDOWNX_MEDIA_PATH ` ?

**Comment by siqinghang** [comment]
@adi-  The automatically generated image url, the image display fails in the preview, because there is one `/` at the far left of the image url, how should I solve this problem?

**Comment by siqinghang** [comment]
I solved this problem by adding the configuration `re_path(r"^uploads/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT, })` to the url. The image is successfully displayed. Preview window.
