### ISSUE TITLE
invalid image upload throws 500

### ISSUE THREAD

**Issue by JeroenvO** [neutronX/django-markdownx#143]
Using latest 2.027 in django 2.1

When trying to upload an invalid image, for instance an .mp4 video the server crashes.
```
Internal Server Error: /markdownx/upload/
Traceback (most recent call last):
  File "x\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "x\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "x\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "x\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "x\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "x\lib\site-packages\django\views\generic\edit.py", line 144, in post
    return self.form_invalid(form)
  File "x\lib\site-packages\markdownx\views.py", line 48, in form_invalid
    response = super(ImageUploadView, self).form_invalid(form)
  File "x\lib\site-packages\django\views\generic\edit.py", line 61, in form_invalid
    return self.render_to_response(self.get_context_data(form=form))
AttributeError: 'ImageUploadView' object has no attribute 'render_to_response'
```

The website hangs and needs to be reloaded to be usable again.

**Comment by JeroenvO** [comment]
https://github.com/neutronX/django-markdownx/blob/master/markdownx/views.py#L48
does not work for ajax requests.

**Comment by adi-** [comment]
Thanx for reporting.

I have check the error and I can accept that it exists. However, I have no clue why Django yells about `object has no attribute 'render_to_response'`. `render_to_response` is a function used by BaseFormView, so it should be working as is.

Any clues? What am I missing?

**Comment by adi-** [comment]
`BaseFormView` class has `FormMixin` which implements `form_invalid` function. Markdownx is using that built-in function, which internally returns `self.render_to_response(self.get_context_data(form=form))`. Why Django cannot see `render_to_response` and returns `AttributeError` becomes a mistery for me.

I can also confirm, that it was working before...

**Comment by JeroenvO** [comment]
When overriding in a custom ImageUploadView with:
```
def form_invalid(self, form):
        return JsonResponse(form.errors, status=400)
```
it works as expected.

**Comment by JeroenvO** [comment]
I cannot find the bug either, but i guess it has to do with templateresponse versus jsonresponse. It makes sense that a jsonresponse doesn't have a template render function...
How about moving line 48 to after the `if` statement, at line 52?

**Comment by adi-** [comment]
> How about moving line 48 to after the `if` statement, at line 52?

Yeah, quite a good idea. However, I wonder what will happen when someone will upload a file by POST
