### ISSUE TITLE
View opacity reset after invalid image upload

### ISSUE THREAD

**Issue by JeroenvO** [neutronX/django-markdownx#144]
When working on https://github.com/neutronX/django-markdownx/issues/143 i noticed the view opacity is not reset after uploading an invalid image.
Proposal: remove `return null` on this line, so the `properties.editor.style.opacity = NORMAL_OPACITY;`
is called correctly.
https://github.com/neutronX/django-markdownx/blob/master/markdownx/static/markdownx/js/markdownx.js#L457

What is the reason to `return null` here?

**Comment by adi-** [comment]
It was made for purpose. I can agree that it is not the best idea, but we had no clue how to inform a user about upload error better.

**Comment by JeroenvO** [comment]
well, i implemented some of the javascript event hooks to display an error message. Then this is no longer necessary uploading a wrong file does not stop any other functions. But the current behavior is more intuitive for user who don't implement the javascript hooks.
Interesting problem indeed.

**Comment by adi-** [comment]
An idea came to my mind. When upload error occurred, we could display error message right where an image markup would show up. I need to check the code later and see if it is possible to implement that using translations. 

But, the hook for the error is really a very good option for more advanced implementations! Thank you.

**Comment by adi-** [comment]
Could you push a pull request?

**Comment by JeroenvO** [comment]
My solutions now is to use a notify box from metroui https://metroui.org.ua/v3/notify.html
using 
```        
let element = document.getElementsByClassName('markdownx');
Object.keys(element).map(key =>
            element[key].addEventListener('markdownx.fileUploadError', event => $.Notify({
                caption: 'File upload failed!',
                content: event.detail[0].__all__.concat().toString(),
                type: 'alert'
            })));
```
as is suggested in your documentation :)

**Comment by JeroenvO** [comment]
@adi- is this what you meant? I am not experienced in typescript so it might not be correct.

**Comment by adi-** [comment]
`return null` changed to text information. Already in master.
