### ISSUE TITLE
Please remove pip from requirements.txt

### ISSUE THREAD

**Issue by aaugustin** [neutronX/django-markdownx#146]
Having pip in requirements.txt is causing an extra copy of pip to be installed in a virtualenv, while I already have it at the system level. This adds 8,4MB to the size of a container image I'm building for no good reason. Most likely anyone who's able to use requirements.txt already has pip installed so it should be safe to remove it.

**Comment by adi-** [comment]
Good point. Will be removed in next version.

**Comment by 2w3** [comment]
I was remove pip at requirements.txt and  sent PR by this Issue.

https://github.com/neutronX/django-markdownx/pull/148

**Comment by adi-** [comment]
Already in master
