### ISSUE TITLE
upload image, Django 2.1, Markdownx 2.0.28

### ISSUE THREAD

**Issue by ybarlev** [neutronX/django-markdownx#151]
Image upload doesn't work on drag-and-drop. Media folder is working with other applications, and all other functionality of markdownx is in tact.

No errors are generated in the console, when the image is droped in the text area

**My bad**. I was trying to drag&drop from a web browser, which didn't work. Image upload DOES work when images are dragged from a file manager.

**Comment by vishvanath45** [comment]
I guess you can close the issue now.
