### ISSUE TITLE
Problem using Code formatting in Markdown

### ISSUE THREAD

**Issue by vishvanath45** [neutronX/django-markdownx#155]
I integrated django-markdownx in my project, Since I was working on a project which aims at helping upcoming programmers, I need to use code display function of markdownx, I seem to have problem using that.   
Refer to image, I tried wrting the code, and it mixes up the formatting.
![markdownx-error](https://user-images.githubusercontent.com/16117380/54343387-acb92700-4664-11e9-8651-1010d547482f.png)
 
Can you tell me how to solve this formatting issue.

**Comment by StanleyDerLurch** [comment]
inside your virtual environment
`pip install pygments`

```py
# in your settiings file
MARKDOWNX_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.codehilite',
]
```
Get a [Pygments Style](https://github.com/richleland/pygments-css)
