### ISSUE TITLE
How can change the cols width of the textarea editor?

### ISSUE THREAD

**Issue by davider80** [neutronX/django-markdownx#158]
I correctly overridden the default template. However I'm wondering if there is a way to change the textarea size to 80 (the cols attribute). Right now it is set to cols=40.

**Comment by StanleyDerLurch** [comment]
Did you try?
```py
# in forms.py
content = forms.CharField(widget=forms.Textarea(attrs={'cols': 80}))
```

**Comment by ppvan** [comment]
@StanleyDerLurch Can you be more specific?
Currently i have 
```
models.py
content = MarkdownxField(widget=forms.Textarea(attrs={"cols": 80}))
```
Cause django to stop because wrong kwagrs
