### ISSUE TITLE
Permission requirements

### ISSUE THREAD

**Issue by wonkybream** [neutronX/django-markdownx#160]
Both upload and markdownify views are missing permissions and there's no mention in documentation about that.

I think that users should be warned about this if their app requires validated user or they don't want anyone to upload stuff without permissions.

This could potentially lead to bigger problems if views are used maliciously.

In my case I handled this by inheriting your views and adding permission requirements manually.

**Comment by adi-** [comment]
>  In my case I handled this by inheriting your views and adding permission requirements manually.
This is the right approach. However, you could paste your case here so maybe it could be included in the future versions. Fill free to open this issue if you feel so.
