### ISSUE TITLE
get_internal_type returns TextField

### ISSUE THREAD

**Issue by Sanquira** [neutronX/django-markdownx#165]
When calling function `get_internal_type()` it should return MarkdownxField and not TextField so it can be distinguished between them.

**Comment by ezarowny** [comment]
I'm not so sure this was a good idea. I think this is causing some issues when creating new databases. I'll reference this in a new PR in case this isn't related.

**Comment by Sanquira** [comment]
So how do we recognize MarkdownxField?

**Comment by adi-** [comment]
By a class?
