### ISSUE TITLE
Problems creating databases with Markdownx fields

### ISSUE THREAD

**Issue by ezarowny** [neutronX/django-markdownx#169]
When I was trying out the new 3.0.0 release, I noticed that my unit tests fail to even start now. I'm getting errors like `django.db.utils.ProgrammingError: column <model>.<column> does not exist` which causes cursor errors like `psycopg2.errors.InvalidCursorName: cursor "_django_curs_4528541120_sync_1" does not exist`. In this case, the specific column is a MarkdownxField.

I'm wondering if it's related to https://github.com/neutronX/django-markdownx/issues/165?

**Comment by adi-** [comment]
That is strange. Could you check if it is due to #165?

**Comment by ezarowny** [comment]
Yeah, I'll try reverting just that commit on a fork.

**Comment by adi-** [comment]
Fixed with https://github.com/neutronX/django-markdownx/commit/8f33cae6c2e0b9cc78af9d50f4f2bd39d3a343b7

**Comment by ezarowny** [comment]
Seems to be working for me. Thanks!
