### ISSUE TITLE
How to disable HTML tag processing in MarkdownxField

### ISSUE THREAD

**Issue by dt-wark** [neutronX/django-markdownx#170]
Hi, I use Markdownx for blog comments.

I do not want markdownify to process the HTML tags entered in the field. What should I do?

**Comment by adi-** [comment]
What you want to achieve? Secure your website or add code examples?

**Comment by dt-wark** [comment]
> What you want to achieve? Secure your website or add code examples?

Sometimes users forget to close html tags or make mistakes in them, and this changes the layout of the blog.

**Comment by adi-** [comment]
So, when you don't want to process html, just do not add `|safe` filter when outputing data in template.

**Comment by dt-wark** [comment]
In this case markdown will not be processed :(

**Comment by dt-wark** [comment]
I guess all I have to do is validate the form for html tags.

If someone sends a comment with html code, then the form will rise exception.

**Comment by adi-** [comment]
Ok, I get it now. Markdown compiler had something like `safe_mode`, but was depreciated in v3.0. Check out this link https://github.com/Python-Markdown/markdown/blob/master/docs/change_log/release-3.0.md#safe_mode-and-html_replacement_text-keywords-deprecated to get more info about the problem.

**Comment by dt-wark** [comment]
Thanks a lot.
