### ISSUE TITLE
Customization doesn't work with columns attribute

### ISSUE THREAD

**Issue by gurugeek** [neutronX/django-markdownx#173]
Apparently the customisation ignores the cols value. Rows are fine and so is style but no matter if I use cols: 1 or cols: '1' any value I pass is ignored 

```
from django.db import models
from django.forms import TextInput, Textarea
from django.contrib import admin
from markdownx.admin import MarkdownxModelAdmin
from markdownx.widgets import AdminMarkdownxWidget

from .models import Post 




class PostAdmin(admin.ModelAdmin):
    formfield_overrides = {
        models.TextField: {'widget': AdminMarkdownxWidget (attrs={'rows': '5', 'cols': '1', 'style': ' font-size: 1.5em; font-family: HelveticaNeue;'})},
     
    }



# Register your models here.
admin.site.register( Post,  PostAdmin)

```

**Comment by adi-** [comment]
I guess this is styling issue. You are running markdownx in Django's Admin. It has styling already applied!

**Comment by gurugeek** [comment]
@adi- thanks for your reply - sorry for my ignorance but how do I change this behaviour ? rows are working properly and so does style. It should be possible to define cols too without having to rewrite the whole CSS. Thanks for your help.

**Comment by adi-** [comment]
@gurugeek no problem. What you want to achieve will be quite difficult, because Django's policy in this aspect is quite - so to speak - inflexible. You have to work on overwriting the classes that Admin imposes in Django. Use styling debugger.

**Comment by gurugeek** [comment]
@adi- thanks again for your reply. May be there is some misunderstanding about the overwriting:

a) I tried using a different package e.g.

```
class PostAdmin(admin.ModelAdmin):
    formfield_overrides = {
        models.TextField: {'widget': AdminMartorWidget (attrs={'rows': 5, 'cols': 120, 'style': ' font-size: 1.5em; font-family: HelveticaNeue;'})},
    
    }
```
in this example both rows and cols are applied correctly and so is the style.

Django Default text area also works fine so I am not sure I understand why is it inflexible in Django itself e.g.

```

class PostAdmin(admin.ModelAdmin):
    formfield_overrides = {
        models.TextField: {'widget': forms.Textarea (attrs={'rows': 5, 'cols': 1, 'style': ' font-size: 1.5em; font-family: HelveticaNeue;'})},
    
    }

```

In this example rows, columns are resized correctly and style applied properly 


now back to MarkdownX (which is awesome especially the drag and drop for images) 

```
class PostAdmin(admin.ModelAdmin):
    formfield_overrides = {
        models.TextField: {'widget': AdminMarkdownxWidget (attrs={'rows': 5, 'cols': 1, 'style': ' font-size: 1.5em; font-family: HelveticaNeue;'})},
    
    }


```

all **but**  cols is applied correctly. So I think there must be an easy way to do it since it works in the other 2 cases.


I found how to change  the preview area by simple editing
```
.markdownx .markdownx-preview {
  margin-left: 0;
  width: 610px
}

```

but indeed the form element is not part of MarkdownX. The issue is that the cols parameter is ignored (and it isn't by using forms.Textarea which does allow to overwrite all elements without touching the CSS but by simply passing attrs).

**Comment by adi-** [comment]
As I said before, this is a problem of Django's styling classes, not django-markdownx.

**Comment by gurugeek** [comment]
Thanks again for your reply. 

@adi- how is it a Django styling class problem if the following works perfectly fine:
```

class PostAdmin(admin.ModelAdmin):
    formfield_overrides = {
        models.TextField: {'widget': forms.Textarea (attrs={'rows': 50, 'cols': 120, 'style': ' font-size: 1.5em; font-family: HelveticaNeue;'})},
    
    }

```
There is no problem if this is something it is not meant to work with MarkdownX and I grateful for all your hard work in the package but the issue with cols is -- as far as  I see -- with the package styling of the AdminMarkdownXWidget  not with Django.
