### ISSUE TITLE
Typo in translation: "Deustch" needs to be changed to "Deutsch"

### ISSUE THREAD

**Issue by SvenMoenig** [neutronX/django-markdownx#209]
The correct German translation for "German" would be "Deutsch" not "Deustch".
https://github.com/neutronX/django-markdownx/blob/30f2930fb3eb76e447c31333cb6c3a66b2786f77/markdownx/locale/de/LC_MESSAGES/django.po#L46

**Comment by adi-** [comment]
Done in commit 14ed783
