### ISSUE TITLE
Create a release for the package

### ISSUE THREAD

**Issue by TheBuky** [neutronX/django-markdownx#216]
Hi,

More than one year since the last release: [v3.0.1](https://github.com/neutronX/django-markdownx/tree/v3.0.1)
Makes it possible to create a new one with the last patches/fixes and add it to PyPI?

Thank

**Comment by xenatisch** [comment]
We have just released a beta version with support for Django 4. It's also available on PyPI.

**Comment by TheBuky** [comment]
Thank you @xenatisch for all this work
