### ISSUE TITLE
Django 4 and file upload produces error

### ISSUE THREAD

**Issue by onno-timmerman** [neutronX/django-markdownx#221]
```
'ImageUploadView' object has no attribute 'render_to_response'
'WSGIRequest' object has no attribute 'is_ajax'
```

It appears that Django 4.0 removed this:
https://docs.djangoproject.com/en/4.0/releases/4.0/#features-removed-in-4-0

**Comment by xenatisch** [comment]
Use the beta version (v4.0.0b1) which available on [PyPI](https://pypi.org/project/django-markdownx/#history).

Add this to your requirements file:

```
django-markdownx>=4.0.0b1
```

We will release v4 once we are sure there are no potential issues. It's been up for a couple of weeks now, and we haven't had any reports, so we might release it soon.

**Comment by tkojima** [comment]
I got a same error as below using django 4.0 + django-markdownx 4.0.0b1:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/edit.py", line 146, in post
    return self.form_invalid(form)
  File "/usr/local/lib/python3.9/site-packages/markdownx/views.py", line 48, in form_invalid
    if self.request.is_ajax():
AttributeError: 'WSGIRequest' object has no attribute 'is_ajax'
```

I think [this line in form_invalid()](https://github.com/neutronX/django-markdownx/blob/v4.0.0-beta.1/markdownx/views.py#L48) should be updated like [form_valid()](https://github.com/neutronX/django-markdownx/blob/v4.0.0-beta.1/markdownx/views.py#L76).

**Comment by cchacholiades** [comment]
Any updates on releasing v4? @xenatisch thanks! 🙏

**Comment by intiocean** [comment]
+1 for a release - I've experimented with the beta version and it appears to be working fine!

**Comment by hengage** [comment]
Has this been released? I have the url import problem and badly need it sorted out
