### ISSUE TITLE
Release for Django 4.0

### ISSUE THREAD

**Issue by joelburton** [neutronX/django-markdownx#239]
The last release on PyPI can't work with Django 4.0 because of the API shift in Django.

The current code does work, and we're putting it in production.

It's mildly inconvenient to have to pin our requirements to a Git commit ID, though. Would it be possible to get a PyPI-uploaded version for Django 4.0?

**Comment by lancegoyke** [comment]
For others experiencing the same problem, I've never pinned to a Git commit ID before.

Here's how I did it with [the most current commit](https://github.com/neutronX/django-markdownx/commit/adcaa9e375a4691bbd16c4e27f8cdfb985366088). I can confirm my Django site is working again.

With pip:

```
python -m pip install git+https://github.com/neutronX/django-markdownx.git@adcaa9e375a4691bbd16c4e27f8cdfb985366088
```

In requirements.txt:

```
django-markdownx @ git+https://github.com/neutronX/django-markdownx.git@adcaa9e375a4691bbd16c4e27f8cdfb985366088
```

**Comment by adi-** [comment]
Done
