### ISSUE TITLE
Cross-Site Scripting (XSS) Vulnerability in Markdown Library

### ISSUE THREAD

**Issue by Ilopesr** [neutronX/django-markdownx#255]
I have encountered a potential cross-site scripting (XSS) vulnerability in the Markdown library. When using the library's show_markdown filter in Django, it is possible for HTML <script> tags to be rendered, which could lead to cross-site scripting attacks. This poses a security risk as it allows the execution of arbitrary scripts on the user's browser.

Steps to reproduce:

Use the Markdown library with the provided show_markdown filter in a Django project.
Pass a Markdown text containing HTML <script> tags as input to the show_markdown filter.
Render the output in a template.
Expected behavior:
The Markdown library should prevent the rendering of HTML <script> tags by default to mitigate the risk of XSS attacks.

Actual behavior:
The library renders the HTML <script> tags, allowing the execution of scripts, which could result in cross-site scripting vulnerabilities.

Impact:
The presence of XSS vulnerabilities in the library can lead to malicious code injection, potentially compromising user data and security.

Proposed solution:
I suggest enhancing the library's security by implementing proper input sanitization or escaping mechanisms to prevent the rendering of HTML <script> tags in the generated HTML output. This will help protect applications using the library from potential XSS attacks.

Please let me know if you need any further information or clarification.

**Comment by adi-** [comment]
Duplicate of https://github.com/neutronX/django-markdownx/issues/163
