### ISSUE TITLE
Editor height grows on inputs

### ISSUE THREAD

**Issue by jgillard** [neutronX/django-markdownx#263]
When typing or even focussing in the editor, the height of the textarea grows:

![height](https://github.com/neutronX/django-markdownx/assets/3770312/9f74d2c6-a396-4a13-9be8-dc899a78c1eb)

I think this behaviour first started in v4.0.4. We first noticed it when upgrading from v4.0.2 to v4.0.7. The latest version v4.0.7 still exhibits this behaviour.

**Comment by adi-** [comment]
Which browser? version + os.

**Comment by jgillard** [comment]
I've tested latest versions of Chrome, Safari & Firefox on a Mac (13.6.3), and all 3 show the issue.

**Comment by juanignaciosl** [comment]
Same here. Version 122.0.6261.128 (Official Build) (64-bit). Arch Linux, Linux 6.8.2-arch2-1, Gnome 46, X11.

**Comment by mgrdcm** [comment]
Just came across this myself (Django 4.2, FireFox and Safari).  Definitely started in [4.0.4](https://github.com/neutronX/django-markdownx/compare/v4.0.3...v4.0.4).

**Comment by adi-** [comment]
Can anyone do tests to confirm that this fixes the problem?

**Comment by mgrdcm** [comment]
> Can anyone do tests to confirm that this fixes the problem?

Hey @adi-!  I had just updated my comment above https://github.com/neutronX/django-markdownx/issues/263#issuecomment-2120363434 to note that https://github.com/neutronX/django-markdownx/issues/263#issuecomment-2038148082 does fix the issue for me when I saw your question.

**Comment by adi-** [comment]
OK, I will do checking on my side too.

**Comment by mgrdcm** [comment]
> OK, I will do checking on my side too.

Thanks so much for your work on this package @adi-!

**Comment by adi-** [comment]
Oh, I understood you wrong. There is a newer version `4.0.7` (https://github.com/neutronX/django-markdownx/releases/tag/v4.0.7) which already has some fixes on that. Can you confirm that `4.0.7` is already working for you?

**Comment by mgrdcm** [comment]
> Oh, I understood you wrong. There is a newer version `4.0.7` (https://github.com/neutronX/django-markdownx/releases/tag/v4.0.7) which already has some fixes on that. Can you confirm that `4.0.7` is already working for you?

No sorry, it is still happening for me in `4.0.7`.

**Comment by adi-** [comment]
os/browser?

**Comment by mgrdcm** [comment]
I'm seeing this on macOS Ventura 13.6.6 with both Safari 17.3.1 and FireFox 127.0b3.

**Comment by jgillard** [comment]
Yep as mentioned in my original post this issue still exists on 4.0.7. I've just retested with that version, and MacOS 14.4.1 and Safari of the same version / Chrome 124 /  Firefox 124.0.2, and the issue persists for all of those.

**Comment by adi-** [comment]
That is really strange. I have tested this on Ubuntu/Firefox, osx/Safari, osx/Firefox and everything looks fine.

Can you verify that web browser's cache was cleared?

**Comment by mgrdcm** [comment]
> Can you verify that web browser's cache was cleared?

Yup!  I tried clearing the cache and even a private browsing window in both Safari and Firefox.

**Comment by kamocat** [comment]
I just installed this plugin for the first time and immediately noticed this issue.
Running Python 3.12 container on rpi, Django 5.0.6, and django-markdownx 4.0.7
Issue shows up in Chrome on both Chrome OS and Windows 11. I didn't test any other browsers.

**Comment by AinoSpring** [comment]
+1
Firefox 129.0
Fedora 40
python3.11
django-markdownx 4.0.7

**Comment by AinoSpring** [comment]
So I managed to fix this by

**Comment by adi-** [comment]
Finally figured out what is going on here. When you want to register model field into admin, you need to use `MarkdownxModelAdmin` base class. I think you forgot about adding it in your `admin.py`. Read about it here: https://neutronx.github.io/django-markdownx/example/#django-admin

P.S. Set height for the editor works as it should.
