### ISSUE TITLE
Is it possible to use extended markdown syntax?

### ISSUE THREAD

**Issue by cgoise** [neutronX/django-markdownx#266]
Hi!

Great plugin, very useful so far.

I have one issue, but maybe you an easy tip for me how to fix it?

I need extended markdown syntax to work, as I work a lot with code blocks and tables. 

Is there a way to achieve this?

Sorry if I abuse github, but this might be the only way to contact you.

Thanks in advance,
Till

**Comment by adi-** [comment]
Of course you can. Check this page in the docs: https://neutronx.github.io/django-markdownx/customization/#markdownx_markdown_extensions
