### ISSUE TITLE
List styling issue

### ISSUE THREAD

**Issue by dzemsxyz** [neutronX/django-markdownx#272]
I'm having an issue with list styling. The list doesn't display correctly when it's not separated by an empty line. See examples below.

Admin:
<img width="366" alt="Screenshot 2024-08-20 at 21 05 35" src="https://github.com/user-attachments/assets/4daa119f-0565-4ebe-8026-644f3b283b45">
Display:
<img width="574" alt="Screenshot 2024-08-20 at 21 04 17" src="https://github.com/user-attachments/assets/d8d88061-46d3-4346-9b81-301383dd5ee3">

**Comment by adi-** [comment]
This is how markdown works...
