### ISSUE TITLE
Support URL reverse

### ISSUE THREAD

**Issue by ziima** [neutronX/django-markdownx#32]
Markdown URL patterns are not reversible. I suggest to

 * add names to the URLs in `markdown.urls`
 * use lazily reversed URLs as defaults for `MARKDOWNX_*_PATH` settings

**Comment by adi-** [comment]
What is your workflow & what exactly you want to achieve?

**Comment by ziima** [comment]
I want to avoid need to copy markdownx URLs to my settings. If I have `markdownx.urls` included in my urlconf, I shouldn't need to define the `MARKDOWNX_*_PATH` settings or I should be able to define them by reversing, similarly to e.g. `LOGIN_URL`.

**Comment by adi-** [comment]
Can you support this with a pull request?
