### ISSUE TITLE
manage.py for testapp

### ISSUE THREAD

**Issue by sfarzy** [neutronX/django-markdownx#47]
Having a `manage.py` file with testapp settings will help beginners like me. Is there any reason to avoid it ? 

Pardon me for being naive.

**Comment by xenatisch** [comment]
I've never seen `manage.py` being included in a stand-alone, reusable app. Such apps are building blocks of a larger website/web service. Once incorporated, the tests can then be run as a part of the actual project.

Whilst our documentations and tests are work in progress, we could perhaps add additional instructions on how to run the tests. Would that be something you'd find helpful?

**Comment by sfarzy** [comment]
Thanks for the info. I was trying to setup the example app and was missing `runserver`.  I got it up with a edited `manage.py`. IMHO instruction on setting a local demo would be nice.

Any additional documentation would be great. :+1:

**Comment by adi-** [comment]
v2 will include full working dev env. However, we just need few more touches to get the final version. Stay tuned.

**Comment by adi-** [comment]
v2 is live. Check out dev.py file.
