### ISSUE TITLE
Drop python 2 support

### ISSUE THREAD

**Issue by adi-** [neutronX/django-markdownx#60]
Django 2.0 is removing Python 2.x support, so as we should do...

**Comment by ezarowny** [comment]
From #105:

> For uploads, I noticed that using django-markdownx with something like django-storages doesn't work because the image stream position is set to the end of the steam when the InMemoryUploadedFile is instantiated. Simply resetting the image stream position back to the beginning should do the trick.
>
> In the future, when you guys drop Python 2 support, something like getbuffer or getvalue could be used to get the length of the buffer instead of using tell.

**Comment by adi-** [comment]
Already in master
