### ISSUE TITLE
Django 1.11 loads widget2.html

### ISSUE THREAD

**Issue by busla** [neutronX/django-markdownx#63]
**Specs:**
Python 3.5.2
Django 1.11
Markdownx 2.0.17 (from pypi)

I´m trying to overwrite the widget to get a [side-by-side pane](http://neutronx.github.io/django-markdownx/example.html#template-customization).

According to the docs, I need to override `widget.html` since I have Django 1.11, although, markdownx is loading `widget2.html`

<img width="696" alt="screen shot 2017-05-01 at 22 06 29" src="https://cloud.githubusercontent.com/assets/3162968/25596769/7b176888-2eba-11e7-9cf1-a91b69697ece.png">

~~When I try to override `widget2.html`, Python crashes with the following traceback:~~

~~Traceback: https://gist.github.com/busla/41b3bf67178118a7f13b99ff30cf9f58~~

My template config is fine, it works for other overridden templates without any problem but here is my template config:

```python
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'core.context_processors.global_data.global_data',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```

I´ve tried:
* `myapp/templates/markdownx/widget2.html`
* `myapp/templates/markdownx/widget.html`
* `myproject/templates/markdownx/widget2.html`
* `myproject/templates/markdownx/widget.html`

~~The traceback looks like an infinite recursion and I checked if I was loading widget2.html in multiple places but that was not the case.~~

**Comment by busla** [comment]
Ok, I feel stupid 😄 

This has nothing todo with markdownx.

There was a typo in my form 😟

**Comment by busla** [comment]
I still can´t override the template though so the original issue persists.

**Comment by busla** [comment]
I should also note that I´m not using `MarkdownxField()` but a regular `TextField()` and the preview works fine.

**Comment by busla** [comment]
So, now when I override `widget2.html` I get this console error:

```javascript
markdownx.js:633 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at http://localhost:8000/static/markdownx/js/markdownx.js:633:17
    at Array.map (native)
    at http://localhost:8000/static/markdownx/js/markdownx.js:631:14
    at Array.map (native)
    at Object.mountEvents (http://localhost:8000/static/markdownx/js/markdownx.js:629:24)
    at _initialize (http://localhost:8000/static/markdownx/js/markdownx.js:364:17)
    at new MarkdownX (http://localhost:8000/static/markdownx/js/markdownx.js:503:5)
    at http://localhost:8000/static/markdownx/js/markdownx.js:566:62
    at Array.map (native)
    at http://localhost:8000/static/markdownx/js/markdownx.js:566:34
```

**Comment by busla** [comment]
Ok, changed according to `widget2.html` documentation and this works.

The outstanding issue is: Django 1.11 is loading `widget2.html` instead of `widget.html`

**Comment by xenatisch** [comment]
Or the documentation is wrong? Not sure which one it is, but one will certainly be corrected.

**Comment by xenatisch** [comment]
Corrected in the docs.
