### ISSUE TITLE
Uncaught TypeError: this.inhibitDefault is not a function

### ISSUE THREAD

**Issue by busla** [neutronX/django-markdownx#64]
I get the following error in the browser console when dragging an image to the editor:

```javascript
Uncaught TypeError: this.inhibitDefault is not a function
    at HTMLTextAreaElement.onDragEnter (markdownx.js:48)
onDragEnter @ markdownx.js:48
markdownx.js:48 Uncaught TypeError: this.inhibitDefault is not a function
    at HTMLTextAreaElement.onDragEnter (markdownx.js:48)
onDragEnter @ markdownx.js:48
```

The image uploads successfully and is displayed in the preview despite of this error.

**Comment by xenatisch** [comment]
Your browser and its version, please. 

That's an event trigger, so it wouldn't have an impact on upload or display. It's primarily there for people who wish to handle these events (e.g. add a spinner or something). 

I'll of course correct the issue, but it wouldn't be at the top of my list.

**Comment by busla** [comment]
Sorry mate, and thanks for looking into this 😄 

* Chrome
* 58.0.3029.81 (64-bit)

**Comment by xenatisch** [comment]
Solved - `inhibitDefault` now behaves as it should.
