### ISSUE TITLE
MARKDOWNX_IMAGE_MAX_SIZE not respected

### ISSUE THREAD

**Issue by busla** [neutronX/django-markdownx#65]
Specs:
* Python 3.5.2
* Django 1.11
* Markdownx 2.0.17 (from pypi)

The uploaded images are never resized. Here is my config:

MARKDOWNX_IMAGE_MAX_SIZE = {
    'size': (500, 500),
    'quality': 90
}

**Comment by xenatisch** [comment]
You sure it's 2.6.8? The latest release is 2.0.17 !

**Comment by busla** [comment]
Oops, was looking at `markdown` 😟 

I´m using `2.0.17`

**Comment by xenatisch** [comment]
Ok... I'll check all your reports in a few hours.
