### ISSUE TITLE
Images rendered strangely

### ISSUE THREAD

**Issue by farice** [neutronX/django-markdownx#69]
I see something like this when images are rendered:

<img width="1128" alt="screen shot 2017-06-07 at 12 28 12 am" src="https://user-images.githubusercontent.com/13244177/26866982-58a192ea-4b18-11e7-86d4-1c9356b5a9c7.png">

Any idea why that's the case? The image itself is presented, but tilted and covering other elements. Why is it presented like this?

I have a standard set-up. In `views.py`

```
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.text = markdownify(post.text)
    return render(request, 'tex/post_detail.html', {'post': post})
```

and in `post_detail.html`

    <p>{{ post.text | safe }}</p>

Other than that, I simply installed with pip, added to my settings, used as a field, etc.. Nothing fancy and no overrides. I added the image with the standard `![]()` syntax.

**Comment by adi-** [comment]
Can you give more details?

**Comment by farice** [comment]
@adi- Are the details I've just added sufficient?

**Comment by adi-** [comment]
I would like to see the image you used as a good start, plus your css – I suspect that it might be a problem with the second.

**Comment by xenatisch** [comment]
Shall we take it that the issue is resolved?
