### ISSUE TITLE
Line breaks in code blocks

### ISSUE THREAD

**Issue by nstahl** [neutronX/django-markdownx#72]
Hello,

I would expect line breaks to be parsed in code blocks.

For example, the markdown

\`\`\`javascript
var x = 1;
var y = 2;
\`\`\`
should render, much like it does on Github, as 
```javascript
var x = 1;
var y = 2;
```
Instead, markdownx renders it as

```javascript
var x = 1; var y = 2;
```

Is that intentional or am I missing something?

Thank you for building markdownx!
-- Niko

**Comment by xenatisch** [comment]
It is not caused by MarkdownX. Rather, it is the Markdown interpreter you are using that's causing it (as I see it). 

![screen shot 2017-06-11 at 11 08 46](https://user-images.githubusercontent.com/13240654/27010182-7df526f2-4e96-11e7-8edb-66020a676788.png)

**Comment by xenatisch** [comment]
How did it go? Let me know if you can't figure out to solve the problem.

**Comment by nstahl** [comment]
Hi @xenatisch -- thanks for your quick response!

I'm not quite sure how to set a Markdown interpreter that can fix this. Can you advise? I'm trying to replicate the functionality that github has for rendering .md files.

Thanks!

**Comment by xenatisch** [comment]
Have you followed the [documentations](https://neutronx.github.io/django-markdownx/index.html), particularly the details on [Markdowify function](https://neutronx.github.io/django-markdownx/customization.html#markdownify)?

**Comment by nstahl** [comment]
Thanks @xenatisch. Your answers were very helpful. I ended up using Github's [API](https://developer.github.com/v3/markdown/) for my use case – it adds all the css needed for code formatting.

**Comment by xenatisch** [comment]
Excellent. Maybe we can suggest the API somewhere in our tutorials so others can also benefit from it. You're welcome to submit it as a contribution if you so wish. 

All the best with your project.

**Comment by djcroissant** [comment]
I had the same issue where line breaks were not rendering correctly in code blocks. I found the issue only occurs when using the backtick notation.

Markdown:
```
line 1
line 2
```

Renders as:
line 1 line 2

However, using the indent notation works.

Markdown:
    line 1
    line 2

Renders as:
line 1
line 2

This behavior is inconsistent with other Markdown rendering tools. But the work-around is easy if you know what to expect.

**Comment by vishvanath45** [comment]
> Have you followed the [documentations](https://neutronx.github.io/django-markdownx/index.html), particularly the details on [Markdowify function](https://neutronx.github.io/django-markdownx/customization.html#markdownify)?

@xenatisch Hi, I am facing the same error in code formatting, the Markdownify function that you mentioned seems to be dead link, can you suggest me how to solve this issue.
