### ISSUE TITLE
how can i change the background color of code block

### ISSUE THREAD

**Issue by hiddensorrow** [neutronX/django-markdownx#73]
Well, I know less about front end.  I want to change my code block to another color(such as black or grey or something else),  which css file should be modified? I could just find the .css in the markdownx/static/markdownx/admin, but the files in this directory seems to change the widget textarea of admin. So, I feel very confused and don't know how to deal with it... 
Could anyone help me? 
Thanks!

**Comment by adi-** [comment]
I can't test it now, but I think you should set css styles for `textarea` inside `.markdownx` class. I guess it is named `.markdownx-editor`.

**Comment by hiddensorrow** [comment]
@adi- hmm, do you mean that i should change the /admin/css/markdownx.css just like this:
```
.markdownx {
  display: inline-block
}
.markdownx .markdownx-editor,
.markdownx .markdownx-preview {
  margin-left: 0;
  width: 610px;
  background-color: #000;
}
```
where I add the background-color and set which to black?
Sorry, I don't know whether I had got your point.

**Comment by adi-** [comment]
No, `/admin/css/markdownx.css` is only for Django Admin forms. You need to add custom css stylesheet.

**Comment by xenatisch** [comment]
You can also use JavaScript, or add a custom CSS for all `.markdownx-preview code` or `.markdownx-preview pre` or both. 

You can also use JavaScript libraries for syntax highlighting. A decent example of this, in my opinion, is [highligh.js](https://highlightjs.org), which support quite a lot of languages, and has many different themes.

**Comment by hiddensorrow** [comment]
@adi- @xenatisch It's very kind of you! Thanks a lot :)
