### ISSUE TITLE
URLs modules docs are missing

### ISSUE THREAD

**Issue by BobHarper1** [neutronX/django-markdownx#79]
http://neutronx.github.io/django-markdownx/markdownx/docs/urls.html

https://github.com/neutronX/django-markdownx/tree/master/docs/markdownx/docs

**Comment by xenatisch** [comment]
Nothing much to say in it, which is why it's not compiled to a webpage. I'll add something about adding the URLs and what are they for at some point. 

Thanks for pointing it out though!

**Comment by adi-** [comment]
Obsolete, closing.
