### ISSUE TITLE
Control size of linked image 

### ISSUE THREAD

**Issue by kvedes** [neutronX/django-markdownx#80]
I'm using markdownx to render markdown for a blog. Some blog posts contain images such as:
```
![picture](http://i.imgur.com/xxxx.png)
```
The images appear when rendering the blog post, but the problem is that I can't control the size of the images. I tried adding the following to the settings.py file as described in the documentation. :
```
MARKDOWNX_IMAGE_MAX_SIZE = {
    'size': (500, 500),
    'quality': 90
}
```
I suspect that this variable only controls the size of images uploaded to the site? Does anyone know how I can control the size of images that are linked in the blog post?

**Comment by xenatisch** [comment]
Your issue is not with MarkdownX, but Markdown as whole, which does not provide such a functionality. I'm afraid the only way around this is to upload the image and let the server-side tools we have implemented take care of it based on your settings.
