### ISSUE TITLE
No module named 'markdownx'

### ISSUE THREAD

**Issue by mtbehisseste** [neutronX/django-markdownx#81]
When deploying my blog to heroku, I got the error "No module named  #'markdownx' ".
`INSTALLED_APPS` in my `settings.py`:
![image](https://user-images.githubusercontent.com/15177509/29105387-9275d602-7cff-11e7-841a-684f752a8395.png)

I don't really know where this error should be traced back to or did I just miss something.
Thank you!

**Comment by xenatisch** [comment]
You haven't installed `django-markdownx` on your server.

**Comment by mtbehisseste** [comment]
Thanks, I add `django-markdownx` to `requirements.txt` and works.
