### ISSUE TITLE
[SOLVED] Render markdown to HTML in template

### ISSUE THREAD

**Issue by alzearafat** [neutronX/django-markdownx#83]
Hi there

I'm new here, and I'm having an issue rendering markdownx to HTML. I use this tag : 

```
{{ post.content|safe }}
```

But it's not working. And I cannot find in the docs (Maybe I missed it?)

Thank you!

**Comment by adi-** [comment]
Most of the info how to properly setup markdownx is written in the docs. Please read it carefully. 

To be able to give you some tips, more info with your issue is needed.

**Comment by alzearafat** [comment]
Thankyou @adi- 

I already read the setup, and it's already working in admin/model. Now I want to display it in template, but not working.

I usually just using this `{{ post.content|safe }}` tag in another WYSIWG editor and just workin fine :/

**Comment by alzearafat** [comment]
I just solved the issue, using template tag filter and `'markdownx.utils.markdownify'` function. This is the steps (I dont know if this is the best way or not, but it works as I expected) : 

1.  I create custom template tag filter : 

```
from django import template
from markdownx.utils import markdownify

register = template.Library()

@register.filter
def show_markdown(text):
    return markdownify(text)
```

2. And then just call it in template : 

```
{{ post.content|show_markdown|safe }}
```

**Comment by xenatisch** [comment]
There are plenty of options to achieve this; most of which take the same approach as you've manually implemented yourself.

Thanks for sharing anyway!

**Comment by tonykyriakidis** [comment]
I completely agree with @denizdogan , this should be in the scope of the project and the documentation could be improved. There should be a section on how to render markdown in templates with a proper/complete example.

**Comment by spatocode** [comment]
I solved the problem in this way. It's probably the easiest way.

_model.py_
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify

class Article(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=100, unique=True)
    content = MarkdownxField()
    
    def formatted_markdown(self):
         return markdownify(self.content)


_template.html_
<article class="content">
       {{ article.formatted_markdown|safe }}
</article>

**Comment by juliocieza** [comment]
> I solved the problem in this way. It's probably the easiest way.
> 
> _model.py_
> from markdownx.models import MarkdownxField
> from markdownx.utils import markdownify
> 
> class Article(models.Model):
> author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
> title = models.CharField(max_length=100, unique=True)
> content = MarkdownxField()
> 
> ```
> def formatted_markdown(self):
>      return markdownify(self.content)
> ```
> 
> _template.html_
> 
> {{ article.formatted_markdown|safe }}

I worked for me, now is rendering ok, but the quotes are not working.

**Comment by jonathan-daniel** [comment]
For anyone coming here for a XSS safe solution: https://github.com/neutronX/django-markdownx/issues/163

**Comment by bitFez** [comment]
I tried the above solutions without much luck. After much fiddling, I managed to pull it off and decided to write this up since I can see other users above also had the same issues as myself.

@alzearafat 
tutorial here: https://blog.devgenius.io/django-markdown-part-1-rendering-it-b61cbcbc833e#6d86-8337ea5bff80
