### ISSUE TITLE
Line don't breaks in code blocks question

### ISSUE THREAD

**Issue by xcainiao** [neutronX/django-markdownx#84]
I try a lot of editors, but it the same.

**Comment by xenatisch** [comment]
This is not about the editor. It's probably a problem with your Markdown interpreter and / or your CSS. See #72 for more information.

**Comment by hseritt** [comment]
I tested this with:
```
```python
var x = 1;
var y = 2;
```
```

And it renders fine. Perhaps the original reporter didn't use the code formatting? In that case, it does show side by side. This should probably be closed unless the original reporter has some steps to reliably show the issue.

**Comment by fanonxr** [comment]
For me I had to wrap the code block I want to use in two backticks `` instead of the standard six ``````
