### ISSUE TITLE
Auto generate <br> tag?

### ISSUE THREAD

**Issue by alzearafat** [neutronX/django-markdownx#87]
Hi

Why django-markdonwx always generate `<br>` on every new line? It makes the content looks ugly :/

Thank you

**Comment by xenatisch** [comment]
MarkdownX doesn't generate anything. It's not a Markdown interpreter. What produces `<br/>` tags on line-breaks is the markdown interpreter you are using. Many interpreters have specific options to enable / disable the conversion of `\n' or '\r` to `<br/>`.

**Comment by alzearafat** [comment]
Hi

Nevermind, my bad. Accidentally add `linebreaks` tag on template :(

Thank you @xenatisch

**Comment by xenatisch** [comment]
@alzearafat Happens. Best of luck.
