### ISSUE TITLE
Customized MARKDOWNX_MEDIA_PATH

### ISSUE THREAD

**Issue by neequole** [neutronX/django-markdownx#92]
Hello,

Based on your [documentation](http://neutronx.github.io/django-markdownx/customization.html#media-path) for customisation of media path, we can set it in our settings.py as `MARKDOWNX_MEDIA_PATH = datetime.now().strftime('markdownx/%Y/%m/%d')`. But if so, I think this will set the datetime to when the Django server was restarted because then the settings.py will be run/read instead of when the file was uploaded?

 Thanks!

**Comment by xenatisch** [comment]
And that's a problem, why? It's a static path, and the files are saved with a random name (UUID). So, why is it a problem if the settings are reset?

**Comment by adi-** [comment]
No response. Closing...
