### ISSUE TITLE
Error with Django 2.0

### ISSUE THREAD

**Issue by w00kie** [neutronX/django-markdownx#95]
When running Django 2.0, I get an `argument to reversed() must be a sequence` when I include `{{ form.media }}` for a markdownx enabled model form.

**Comment by w00kie** [comment]
I just saw PR #94, tested it and confirmed it fixes my issue.

**Comment by xenatisch** [comment]
I will merge that later this week, or at some point next week.

**Comment by w00kie** [comment]
Hello @xenatisch 
Do you have any updates on this?

**Comment by xenatisch** [comment]
@pawel2g done.

**Comment by aeyoll** [comment]
Hello @xenatisch,
Thanks for the merge. Is this publishable to PyPi? It would be nice to have a Django 2.0 compatible version for this great package. 
Thanks a lot!

**Comment by adi-** [comment]
It is live with v2.0.22
