### ISSUE TITLE
Are the tables supported?

### ISSUE THREAD

**Issue by trecker** [neutronX/django-markdownx#97]
Does this support table syntax,
```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned |       |
| col 2 is      | centered      |       |
| zebra stripes | are neat      |       |
```
Result:
```html
<p>| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned |  |
| col 2 is      | centered      |    |
| zebra stripes | are neat      |     |</p>
```

Need:

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned |       |
| col 2 is      | centered      |       |
| zebra stripes | are neat      |       |

```html
<table>
<thead>
<tr>
<th>Tables</th>
<th align="center">Are</th>
<th align="right">Cool</th>
</tr>
</thead>
<tbody>
<tr>
<td>col 3 is</td>
<td align="center">right-aligned</td>
<td align="right"></td>
</tr>
<tr>
<td>col 2 is</td>
<td align="center">centered</td>
<td align="right"></td>
</tr>
<tr>
<td>zebra stripes</td>
<td align="center">are neat</td>
<td align="right"></td>
</tr></tbody></table>
```

**Comment by xenatisch** [comment]
It depends on the Markdown interpreter that you use. See the [documentations](http://neutronx.github.io/django-markdownx/customization.html#markdownify) for additional information.

**Comment by trecker** [comment]
I use the default settings

**Comment by xenatisch** [comment]
But you want a special feature, so you need to make sure that the specific feature you're looking for is either supported by the Markdown interpreter, or the interpreter has an extension for supporting that feature. [Here](https://pythonhosted.org/Markdown/extensions/index.html#officially-supported-extensions) is a list of extensions available to you. 

You can use appropriate settings as explained [here in the documentations](http://neutronx.github.io/django-markdownx/customization.html#extension-configurations) to enable the use of that a specific extension in the default interpreter.

**Comment by trecker** [comment]
Thank you very much!
