### ISSUE TITLE
Widget Customisation: Setting Class Attribute Takes No Effect

### ISSUE THREAD

**Issue by thaxy** [neutronX/django-markdownx#99]
Given the following ModelForm:

```
class ModelForm(forms.ModelForm):

    class Meta:
        model = Model
        fields = (
            "title",
            "content"
        )
        widgets = {
            "content": MarkdownxWidget(attrs={'class': 'bla', 'style': 'resize:none; width: 100%;'}),
        }
```

Results in:
`<textarea class="markdownx-editor" style="resize: none; width: 100%; transition: opacity 1s ease 0s;" ...></textarea>`

Somehow https://github.com/neutronX/django-markdownx/blob/master/markdownx/widgets.py#L81 doesn't seem to work.

Tested with ``Django==1.11.3``,  ``django-markdownx==2.0.21`` and ``Python 3.5``.

_______

``widget2.html``:

```
<div class="markdownx row">
    <div class="col-md-6">
        {% include 'django/forms/widgets/textarea.html' %}
    </div>
    <div class="col-md-6">
        <div class="markdownx-preview"></div>
    </div>
</div>
```

``settings.py``:
```
[...]
INSTALLED_APPS = [
    ...,
    'django.forms',
    'markdownx',
    ...
]

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

[...]
```

**Comment by dhavalsavalia** [comment]
Did you solve it?

**Comment by nessalc** [comment]
A hack that worked for me for now is this:
Edit `add_markdownx_attrs` (in markdownx.widgets) to the following:

```
        if 'class' in attrs.keys():
            attrs['class'] += ' markdownx-editor form-control'
        else:
            attrs.update({
                'class': 'markdownx-editor form-control'
            })
```

**Comment by dhavalsavalia** [comment]
@nessalc do you know how to use multiple editors on the same page?

**Comment by nessalc** [comment]
@dhavalsavalia I've not done it myself, and this is probably the wrong place for that question, but I'll give you [this link to a StackOverflow article explaining one way to do it](https://stackoverflow.com/questions/50914186/how-to-use-multiple-django-markdownx-editors-on-the-same-page).
